#!/usr/bin/env bash
# Install nginx on web-01 server; Nginx should be listnning to port 80

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
