#!/usr/bin/env bash
# Displays "Best School" 10 times using an until loop.
# Initialize a counter variable called 'count' to 0.
count=0
# Start an until loop that will continue until 'count' equals 10.
until [ $count -eq 10 ]
do
  echo "Best School"
  (( count++ ))
done
